# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4964cb5dbc4f571a900e50c646f5c9328642968db2ab7cb29cdddea210082f1cfc1343a14b21d530667f7db73260fa0186528f308d6371cf52302ebc032c7591

test:
  secret_key_base: 316866783d69dcd947504bbbf96e75f8e66563f82e143f8bab0b99552887d5a5456b88b348e8a68d9527a98bc13cc9d24669284e66477f81537c0a2967152317

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
